version: '3'
services:
  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: SecretPassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - db
