version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./crawldb.sql:/docker-entrypoint-initdb.d/crawldb.sql
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - db