version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - './postgres_db:/var/lib/postgresql/data'
      - './api/src/sql_scripts:/docker-entrypoint-initdb.d'

