version: "3" 

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api/src:/app
    networks:
      - my_network
    environment:
      CLOUD_SQL_USER: ${CLOUD_SQL_USER}
      CLOUD_SQL_PASSWORD: ${CLOUD_SQL_PASSWORD}
      CLOUD_SQL_DATABASE: ${CLOUD_SQL_DATABASE}
      CLOUD_SQL_HOST: ${CLOUD_SQL_HOST}
      CLOUD_SQL_PORT: ${CLOUD_SQL_PORT}

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33
    volumes:
      - ./${SERVICE_ACCOUNT_FILE}:/app/service-account-file.json 
    command: /cloud_sql_proxy -instances=${INSTANCE_CONNECTION_NAME}=tcp:0.0.0.0:5432 -credential_file=/app/service-account-file.json
    networks:
      - my_network

  notebook:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./client/src:/app
    networks:
      - my_network

networks:
  my_network: